### ISSUE TITLE
Any ideas for this message?

### ISSUE THREAD

**Issue by ask4jm** [vackar/BayesISOLA#2]
Pre-calculated grid point 0 was calculated with different parameters. File green/station.dat has different hash, probably station set was different.
/home/user/BayesISOLA/BayesISOLA/_inverse.py:73: RuntimeWarning: overflow encountered in exp
  GP['c'] = np.sqrt(gp['det_Ca']) * np.exp(-0.5 * (GP['misfit']-min_misfit))
/home/user/BayesISOLA/BayesISOLA/_inverse.py:73: RuntimeWarning: overflow encountered in scalar multiply
  GP['c'] = np.sqrt(gp['det_Ca']) * np.exp(-0.5 * (GP['misfit']-min_misfit))
/home/user/BayesISOLA/BayesISOLA/_plot_solution_maps.py:186: RuntimeWarning: invalid value encountered in scalar divide
  width.append(self.grid.step_x*1e-3 * np.sqrt(g[x][y]['c'] / max_c))
/home/user/BayesISOLA/BayesISOLA/_plot_solution_summary.py:74: RuntimeWarning: invalid value encountered in scalar divide
  n_GP = int(round(GP['c'] / self.MT.sum_c * n))
Traceback (most recent call last):
  File "./test1.py", line 42, in <module>
    plot = BayesISOLA.plot(solution)
  File "/home/user/BayesISOLA/BayesISOLA/plot.py", line 65, in __init__
    self.plot_uncertainty(n=uncertainty)
  File "/home/user/BayesISOLA/BayesISOLA/_plot_solution_summary.py", line 74, in plot_uncertainty
    n_GP = int(round(GP['c'] / self.MT.sum_c * n))
ValueError: cannot convert float NaN to integer

**Comment by ask4jm** [comment]
Sorry there was a pzfile issue. After fixing it new message is:

Pre-calculated grid point 0 was calculated with different parameters. Its coordinates differs, probably the shape of the grid was changed.
Minimal eigenvalue C[0]: -6.3e-18, clipping
Minimal eigenvalue C_inv: -6.8e+33+0.0e+00j, CLIPPING
/home/user/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/user/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/user/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Thanks for your time

**Comment by vackar** [comment]
Hi, now it seems there are just warnings you can ignore. I recommend you 
to check the uncertainty and stability of the solution always, 
especially in cases you see such warnings. You can inspect it using the 
histograms, the plot with multiple beachballs, and the condition number 
(as lower the solution is more stable; CN < 10 is fine).

Jiri
